import type {
  Site, Sale, Incident, CustomerFeedback, Kaizen, PDCA, Insight, DailyBriefing
} from './types'

export const mockSite: Site = {
  id: 'site-franconville',
  name: 'Franconville',
  address: '12 Rue du Commerce, 95130 Franconville',
  manager_name: 'Simon Gohier',
}

export const mockBriefing: DailyBriefing = {
  site_id: 'site-franconville',
  date: new Date().toISOString().split('T')[0],
  responsible: 'Simon',
  adjoint: 'Clémentine',
  objectives: [
    'Atteindre 12 500 € de CA journalier',
    'Clôturer 2 incidents logistiques ouverts',
    'Accueillir le groupe scolaire 14h-16h',
  ],
  team: [
    { name: 'Simon', role: 'Directeur', present: true },
    { name: 'Clémentine', role: 'Adjointe', present: true },
    { name: 'Celia', role: 'Resp. Zone', present: true },
    { name: 'Sokaina', role: 'Trampoline Réf.', present: true },
    { name: 'Iliane', role: 'Trampoline', present: true },
    { name: 'Sophie', role: 'Trampoline', present: true },
    { name: 'Aylin', role: 'Trampoline', present: true },
    { name: 'Amina', role: 'Trampoline', present: true },
    { name: 'Elson', role: 'Trampoline', present: true },
    { name: 'Benoit', role: 'Trampoline', present: true },
    { name: 'Myriam', role: 'Caisse Réf.', present: true },
    { name: 'Naïma', role: 'Caisse', present: true },
    { name: 'Hanya', role: 'Caisse', present: true },
    { name: 'Lina', role: 'Caisse', present: true },
    { name: 'Asmaa', role: 'Anniversaire', present: true },
    { name: 'Corian', role: 'Anniversaire', present: true },
    { name: 'Line', role: 'Anniversaire', present: true },
    { name: 'Lya', role: 'Restauration', present: true },
    { name: 'Swen', role: 'Restauration', present: true },
    { name: 'Ludo', role: 'Restauration', present: true },
  ],
}

// Generate 30 days of sales data
export const mockSales: Sale[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date()
  date.setDate(date.getDate() - (29 - i))
  const target = 11000 + Math.random() * 2000
  const variance = (Math.random() - 0.4) * 3000
  return {
    id: `sale-${i}`,
    site_id: 'site-franconville',
    date: date.toISOString().split('T')[0],
    amount: Math.max(6000, target + variance),
    target,
    period: 'day',
  }
})

export const mockIncidents: Incident[] = [
  {
    id: 'inc-1',
    site_id: 'site-franconville',
    description: 'Filet trampoline endommagé zone 3 — mise hors service temporaire',
    category: 'quality',
    impact: 'high',
    owner: 'Thomas',
    status: 'action_ongoing',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inc-2',
    site_id: 'site-franconville',
    description: 'Retard livraison frites — rupture stock 30 min',
    category: 'logistics',
    impact: 'medium',
    owner: 'Joanna',
    status: 'verified',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inc-3',
    site_id: 'site-franconville',
    description: 'Système caisse lent — temps d\'attente augmenté',
    category: 'it',
    impact: 'medium',
    owner: 'Myriam',
    status: 'declared',
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inc-4',
    site_id: 'site-franconville',
    description: 'Procédure d\'évacuation non respectée lors exercice',
    category: 'security',
    impact: 'high',
    owner: 'Simon',
    status: 'action_ongoing',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inc-5',
    site_id: 'site-franconville',
    description: 'Client blessé légèrement sur escalier — rapport rempli',
    category: 'client',
    impact: 'high',
    owner: 'Clémentine',
    status: 'standardised',
    created_at: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inc-6',
    site_id: 'site-franconville',
    description: 'Musique en panne salle principale 2h',
    category: 'it',
    impact: 'low',
    owner: 'Thomas',
    status: 'verified',
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inc-7',
    site_id: 'site-franconville',
    description: 'Sous-effectif samedi après-midi — files d\'attente caisse',
    category: 'process',
    impact: 'medium',
    owner: 'Clémentine',
    status: 'declared',
    created_at: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inc-8',
    site_id: 'site-franconville',
    description: 'Nettoyage vestiaires insuffisant signalé par client',
    category: 'quality',
    impact: 'low',
    owner: 'Celia',
    status: 'verified',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
]

export const mockFeedback: CustomerFeedback[] = [
  {
    id: 'fb-1',
    site_id: 'site-franconville',
    type: 'satisfaction',
    category: 'compliment',
    description: 'Super accueil de l\'équipe, les enfants ont adoré !',
    sentiment: 'positive',
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'fb-2',
    site_id: 'site-franconville',
    type: 'complaint',
    category: 'quality_issue',
    description: 'Filet abîmé dans la zone enfants, dangereux',
    sentiment: 'negative',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'fb-3',
    site_id: 'site-franconville',
    type: 'complaint',
    category: 'service_issue',
    description: 'Attente trop longue à la caisse le samedi',
    sentiment: 'negative',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'fb-4',
    site_id: 'site-franconville',
    type: 'satisfaction',
    category: 'positive_experience',
    description: 'Animation anniversaire excellente, très professionnel',
    sentiment: 'positive',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'fb-5',
    site_id: 'site-franconville',
    type: 'complaint',
    category: 'remark',
    description: 'Vestiaires un peu sales en fin de journée',
    sentiment: 'neutral',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'fb-6',
    site_id: 'site-franconville',
    type: 'satisfaction',
    category: 'compliment',
    description: 'Personnel très sympathique et attentionné',
    sentiment: 'positive',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'fb-7',
    site_id: 'site-franconville',
    type: 'complaint',
    category: 'quality_issue',
    description: 'Boisson froide commandée servie à température ambiante',
    sentiment: 'negative',
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'fb-8',
    site_id: 'site-franconville',
    type: 'satisfaction',
    category: 'positive_experience',
    description: 'Parfait pour un anniversaire, on reviendra !',
    sentiment: 'positive',
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
]

export const mockKaizen: Kaizen[] = [
  {
    id: 'kz-1',
    site_id: 'site-franconville',
    author: 'Thomas',
    description: 'Créer un système de rotation des trampolines pour éviter l\'usure prématurée',
    estimated_gain: 3000,
    real_gain: 2800,
    status: 'implemented',
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'kz-2',
    site_id: 'site-franconville',
    author: 'Myriam',
    description: 'Formulaire de pré-réservation en ligne pour réduire l\'attente caisse',
    estimated_gain: 1500,
    status: 'in_progress',
    created_at: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'kz-3',
    site_id: 'site-franconville',
    author: 'Joanna',
    description: 'Revoir les horaires de livraison food pour coller aux pics d\'affluence',
    estimated_gain: 800,
    status: 'idea',
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'kz-4',
    site_id: 'site-franconville',
    author: 'Celia',
    description: 'Check-list nettoyage digitale avec validation par responsable de zone',
    estimated_gain: 500,
    status: 'in_progress',
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'kz-5',
    site_id: 'site-franconville',
    author: 'Simon',
    description: 'Affichage des temps d\'attente estimés à l\'entrée',
    estimated_gain: 1200,
    status: 'idea',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
]

export const mockPDCA: PDCA[] = [
  {
    id: 'pdca-1',
    site_id: 'site-franconville',
    problem: 'Temps d\'attente caisse > 5 min les week-ends',
    objective: 'Réduire le temps d\'attente à < 2 min',
    action: 'Ouvrir une 2e caisse dès 50 personnes présentes',
    result: 'Temps moyen réduit à 2.5 min',
    standardization: 'Protocole d\'ouverture 2e caisse documenté',
    status: 'act',
    created_at: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'pdca-2',
    site_id: 'site-franconville',
    problem: 'Incidents de chute en zone trampoline récurrents',
    objective: 'Zéro incident de chute par mois',
    action: 'Briefing sécurité obligatoire avant saut + moniteur présent',
    result: 'En cours d\'évaluation',
    standardization: '',
    status: 'do',
    created_at: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'pdca-3',
    site_id: 'site-franconville',
    problem: 'CA food en dessous de l\'objectif (-15%)',
    objective: 'Atteindre 20% du CA total sur le food',
    action: 'Formation upsell équipe + offre combo visible',
    result: '',
    standardization: '',
    status: 'plan',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
]


export const mockInsights: Insight[] = [
  {
    id: 'ins-1',
    site_id: 'site-franconville',
    message: 'Les incidents logistiques ont augmenté de 40% sur les 3 dernières semaines. Une analyse des causes est recommandée.',
    type: 'warning',
    category: 'logistics',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ins-2',
    site_id: 'site-franconville',
    message: 'Le CA de mercredi dernier (+18% vs objectif) coïncide avec la présence d\'un groupe scolaire. À reproduire.',
    type: 'improvement',
    category: 'performance',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ins-3',
    site_id: 'site-franconville',
    message: '3 retours clients négatifs sur la qualité cette semaine — tendance à surveiller.',
    type: 'warning',
    category: 'quality',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ins-4',
    site_id: 'site-franconville',
    message: 'Kaizen "rotation trampolines" implémenté avec succès — économie estimée de 2 800 €.',
    type: 'improvement',
    category: 'kaizen',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ins-5',
    site_id: 'site-franconville',
    message: 'PDCA file d\'attente caisse en phase ACT — standardisation à documenter.',
    type: 'info',
    category: 'pdca',
    created_at: new Date().toISOString(),
  },
]
